# Generated by Django 4.2.16 on 2025-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_store_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('fashion', 'Fashion'), ('tech', 'Tech'), ('grocery', 'Grocery')], default='home', help_text='Select the category for this deal', max_length=20),
        ),
    ]
