# Generated by Django 4.2.16 on 2025-08-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_deal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
